// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJsLmNP59KCa3J5WhGIu8Ly5j6h1vGv7k',
    appId: '1:337650886711:web:8727a2ea6cf94701c9f7b2',
    messagingSenderId: '337650886711',
    projectId: 'romaquest-9f832',
    authDomain: 'romaquest-9f832.firebaseapp.com',
    storageBucket: 'romaquest-9f832.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDjvTAJz0vve82wdfSq-pr1J5Ue6nYtbM',
    appId: '1:337650886711:android:fd511d0710f2f1ecc9f7b2',
    messagingSenderId: '337650886711',
    projectId: 'romaquest-9f832',
    storageBucket: 'romaquest-9f832.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9tyxsc6K1N6RN4UJU67COXlrTXRzDO58',
    appId: '1:337650886711:ios:5ee514ddff16506ac9f7b2',
    messagingSenderId: '337650886711',
    projectId: 'romaquest-9f832',
    storageBucket: 'romaquest-9f832.appspot.com',
    iosBundleId: 'com.example.sampleProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9tyxsc6K1N6RN4UJU67COXlrTXRzDO58',
    appId: '1:337650886711:ios:5ee514ddff16506ac9f7b2',
    messagingSenderId: '337650886711',
    projectId: 'romaquest-9f832',
    storageBucket: 'romaquest-9f832.appspot.com',
    iosBundleId: 'com.example.sampleProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJsLmNP59KCa3J5WhGIu8Ly5j6h1vGv7k',
    appId: '1:337650886711:web:4139bfc5e1280cbbc9f7b2',
    messagingSenderId: '337650886711',
    projectId: 'romaquest-9f832',
    authDomain: 'romaquest-9f832.firebaseapp.com',
    storageBucket: 'romaquest-9f832.appspot.com',
  );
}
